### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by pedrohenriquebraga** [pedrohenriquebraga/tempoou#1]
# Features planejadas para serem adicionadas

Conforme às features são adicionadas eu informo a vocês através dessa issue (isso não significa que elas estarão públicas). Você também pode sugerir novidades e alterações comentando nessa issue.

- [x] Sistema de notificação
- [x] Medidas configuráveis
- [x] Entrar automaticamente na cidade atual através da localização
   - [x] Adicionar suporte a localização
   - [x] Pesquisa por latitude e longitude
   - [x] Pesquisa por nome da cidade (mesmo com localização ativa)
- [ ] Publicar na PlayStore
~Publicar na AppStore~ ***cancelada***
